export interface ClassSlot {
  id: string;
  subject: string;
  code: string;
  type: "Lecture" | "Tutorial" | "Practice" | "Test";
  room: string;
  day: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
  startTime: string; // HH:mm (24h)
  endTime: string;
  timeLabel: string;
  color: string;
  bgLight: string;
  notes?: string;
  isTest?: boolean;
}

export const TIMETABLE_CLASSES: ClassSlot[] = [
  // MONDAY
  {
    id: "mon-dpp-lec",
    subject: "DPP (Design Processes & Perspectives)",
    code: "DES201",
    type: "Lecture",
    room: "A106",
    day: "Monday",
    startTime: "11:00",
    endTime: "12:30",
    timeLabel: "11:00 AM – 12:30 PM",
    color: "border-purple-500/40 text-purple-300",
    bgLight: "bg-purple-500/10 hover:bg-purple-500/20",
    notes: "Design studio ideation, case studies & critique.",
  },
  {
    id: "mon-os-lec",
    subject: "Operating Systems (OS)",
    code: "CSE231",
    type: "Lecture",
    room: "C201",
    day: "Monday",
    startTime: "15:00",
    endTime: "16:30",
    timeLabel: "3:00 – 4:30 PM",
    color: "border-cyan-500/40 text-cyan-300",
    bgLight: "bg-cyan-500/10 hover:bg-cyan-500/20",
    notes: "Processes, Threads, CPU Scheduling & Concurrency.",
  },

  // TUESDAY
  {
    id: "tue-rmssd-lec",
    subject: "RMSSD (Research Methods in Social Sciences & Design)",
    code: "SSH201",
    type: "Lecture",
    room: "C11",
    day: "Tuesday",
    startTime: "11:00",
    endTime: "12:30",
    timeLabel: "11:00 AM – 12:30 PM",
    color: "border-amber-500/40 text-amber-300",
    bgLight: "bg-amber-500/10 hover:bg-amber-500/20",
    notes: "Qualitative/quantitative research methodologies.",
  },
  {
    id: "tue-m3-tut",
    subject: "Math III Tutorial (Graded Weekly Test)",
    code: "MTH201",
    type: "Test",
    room: "Tutorial Room",
    day: "Tuesday",
    startTime: "13:30",
    endTime: "15:00",
    timeLabel: "1:30 – 3:00 PM",
    color: "border-rose-500/60 text-rose-300",
    bgLight: "bg-rose-500/15 hover:bg-rose-500/25 ring-1 ring-rose-500/30",
    notes: "🔥 Weekly Graded Tutorial Test! High impact on final grade.",
    isTest: true,
  },
  {
    id: "tue-ap-lec",
    subject: "Advanced Programming (AP)",
    code: "CSE201",
    type: "Lecture",
    room: "C21",
    day: "Tuesday",
    startTime: "15:00",
    endTime: "16:30",
    timeLabel: "3:00 – 4:30 PM",
    color: "border-emerald-500/40 text-emerald-300",
    bgLight: "bg-emerald-500/10 hover:bg-emerald-500/20",
    notes: "OOP Design Patterns, Java/C++ Concurrency & Architecture.",
  },
  {
    id: "tue-m3-lec",
    subject: "Math III (Differential Equations & Multivariable)",
    code: "MTH201",
    type: "Lecture",
    room: "C201",
    day: "Tuesday",
    startTime: "16:30",
    endTime: "18:00",
    timeLabel: "4:30 – 6:00 PM",
    color: "border-indigo-500/40 text-indigo-300",
    bgLight: "bg-indigo-500/10 hover:bg-indigo-500/20",
    notes: "Thomas Calculus 11th Edition: Partial Derivatives, Multiple Integrals & ODEs.",
  },

  // WEDNESDAY
  {
    id: "wed-os-tut",
    subject: "Operating Systems (OS) Tutorial",
    code: "CSE231",
    type: "Tutorial",
    room: "C101",
    day: "Wednesday",
    startTime: "08:30",
    endTime: "09:30",
    timeLabel: "8:30 – 9:30 AM",
    color: "border-cyan-500/40 text-cyan-300",
    bgLight: "bg-cyan-500/10 hover:bg-cyan-500/20",
    notes: "Hands-on problem solving on scheduling algorithms & memory.",
  },
  {
    id: "wed-ap-tut",
    subject: "Advanced Programming (AP) Tutorial",
    code: "CSE201",
    type: "Tutorial",
    room: "Tutorial Room",
    day: "Wednesday",
    startTime: "14:00",
    endTime: "15:00",
    timeLabel: "2:00 – 3:00 PM",
    color: "border-emerald-500/40 text-emerald-300",
    bgLight: "bg-emerald-500/10 hover:bg-emerald-500/20",
    notes: "Code review, design pattern walkthroughs & quiz revisions.",
  },
  {
    id: "wed-os-lec",
    subject: "Operating Systems (OS)",
    code: "CSE231",
    type: "Lecture",
    room: "C201",
    day: "Wednesday",
    startTime: "15:00",
    endTime: "16:30",
    timeLabel: "3:00 – 4:30 PM",
    color: "border-cyan-500/40 text-cyan-300",
    bgLight: "bg-cyan-500/10 hover:bg-cyan-500/20",
    notes: "Deadlock prevention, Memory virtualization & Paging.",
  },

  // THURSDAY
  {
    id: "thu-rmssd-lab",
    subject: "RMSSD Lab (Research & Data Analysis)",
    code: "SSH201",
    type: "Practice",
    room: "C01",
    day: "Thursday",
    startTime: "09:30",
    endTime: "11:00",
    timeLabel: "9:30 – 11:00 AM",
    color: "border-amber-500/40 text-amber-300",
    bgLight: "bg-amber-500/10 hover:bg-amber-500/20",
    notes: "Qualitative coding & statistical software practicals.",
  },
  {
    id: "thu-dpp-lec",
    subject: "DPP (Design Processes & Perspectives)",
    code: "DES201",
    type: "Lecture",
    room: "A106",
    day: "Thursday",
    startTime: "11:00",
    endTime: "12:30",
    timeLabel: "11:00 AM – 12:30 PM",
    color: "border-purple-500/40 text-purple-300",
    bgLight: "bg-purple-500/10 hover:bg-purple-500/20",
    notes: "Design heuristics, usability testing & visual presentation.",
  },
  {
    id: "thu-ap-lec",
    subject: "Advanced Programming (AP)",
    code: "CSE201",
    type: "Lecture",
    room: "C21",
    day: "Thursday",
    startTime: "15:00",
    endTime: "16:30",
    timeLabel: "3:00 – 4:30 PM",
    color: "border-emerald-500/40 text-emerald-300",
    bgLight: "bg-emerald-500/10 hover:bg-emerald-500/20",
    notes: "Multi-threading, synchronization primitives & memory model.",
  },
  {
    id: "thu-m3-lec",
    subject: "Math III (Differential Equations & Multivariable)",
    code: "MTH201",
    type: "Lecture",
    room: "C102",
    day: "Thursday",
    startTime: "16:30",
    endTime: "18:00",
    timeLabel: "4:30 – 6:00 PM",
    color: "border-indigo-500/40 text-indigo-300",
    bgLight: "bg-indigo-500/10 hover:bg-indigo-500/20",
    notes: "Line integrals, Green's Theorem & Stokes' Theorem.",
  },

  // FRIDAY
  {
    id: "fri-rmssd-lec",
    subject: "RMSSD (Research Methods in Social Sciences & Design)",
    code: "SSH201",
    type: "Lecture",
    room: "C11",
    day: "Friday",
    startTime: "11:00",
    endTime: "12:30",
    timeLabel: "11:00 AM – 12:30 PM",
    color: "border-amber-500/40 text-amber-300",
    bgLight: "bg-amber-500/10 hover:bg-amber-500/20",
    notes: "Mixed methods synthesis, peer presentations & ethics.",
  },
  {
    id: "fri-dpp-studio",
    subject: "DPP Practice Studio",
    code: "DES201",
    type: "Practice",
    room: "A106",
    day: "Friday",
    startTime: "14:00",
    endTime: "17:00",
    timeLabel: "2:00 – 5:00 PM",
    color: "border-purple-500/40 text-purple-300",
    bgLight: "bg-purple-500/10 hover:bg-purple-500/20",
    notes: "Studio prototyping, critique and iterative design feedback.",
  },
];
