'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Sparkles,
  CheckCircle2,
  Calendar,
  Clock,
  Loader2,
  ChevronRight,
  BookOpen,
  CalendarPlus,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { MathView } from '@/components/ui/math-view';
import { ClassScheduleItem } from '@/lib/homework-prompt-engine';
import { OKFRegistry } from '@/lib/okf-indexer';

import { pushToFirestore } from '@/lib/firebase/firestore-sync';

interface HomeworkLoggerModalProps {
  isOpen: boolean;
  classItem: ClassScheduleItem;
  onClose: () => void;
  onSaved: (summary: string) => void;
}

export function HomeworkLoggerModal({
  isOpen,
  classItem,
  onClose,
  onSaved,
}: HomeworkLoggerModalProps) {
  const [inputText, setInputText] = useState('');
  const [loading, setLoading] = useState(false);
  const [previewData, setPreviewData] = useState<any>(null);
  const [savedSuccess, setSavedSuccess] = useState(false);

  if (!isOpen) return null;

  const handleFormatWithAI = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim()) return;

    setLoading(true);
    try {
      const res = await fetch('/api/homework/ai-format', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          rawInput: inputText,
          courseCode: classItem.courseCode,
          courseName: classItem.courseName,
          room: classItem.room,
          classEndTime: classItem.endTime,
          currentDay: classItem.dayName,
        }),
      });

      if (res.ok) {
        const json = await res.json();
        setPreviewData(json.data);
      }
    } catch (err) {
      console.error('Failed to format homework with AI', err);
    } finally {
      setLoading(false);
    }
  };

  const handleConfirmSave = () => {
    if (!previewData && !inputText) return;

    const rawProblems = previewData?.problems || [];
    const summary = previewData?.summary || inputText;
    const smartSchedule = previewData?.smartSchedule;

    const problems = rawProblems.map((p: any) => ({
      ...p,
      rawInput: inputText,
    }));

    // 1. Save to Course Problem Ledger across matching course aliases
    const targetCourseKeys = [
      `learny-problems-${classItem.courseId}`,
      `learny-problems-${classItem.courseCode.toLowerCase()}`,
    ];

    if (classItem.courseCode.toLowerCase().includes('mth') || classItem.courseName.toLowerCase().includes('math')) {
      targetCourseKeys.push('learny-problems-mth203', 'learny-problems-mth201', 'learny-problems-math');
    }

    targetCourseKeys.forEach((key) => {
      localStorage.setItem(key, JSON.stringify(problems));
    });

    // 2. Save to Course Homework Shorthand Input & Lecture Backlog
    localStorage.setItem(`learny-hw-input-${classItem.courseId}`, inputText);
    localStorage.setItem(`learny-backlog-hw-${classItem.id}`, JSON.stringify({
      rawInput: inputText,
      summary,
      problems,
      dueDate: smartSchedule?.dueDate || new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      savedAt: new Date().toISOString(),
      courseCode: classItem.courseCode,
      courseName: classItem.courseName,
    }));

    // 3. Mark class as logged for today & dismiss prompt
    const today = new Date().toISOString().split('T')[0];
    localStorage.setItem(`learny-hw-logged-${today}-${classItem.id}`, 'logged');
    localStorage.removeItem('learny-simulated-class-prompt');

    // 4. Update OKF Google Drive Manifest
    const lectureId = `iiitd-${classItem.courseId.toLowerCase()}-lec02`;
    OKFRegistry.updateLectureHomework(lectureId, inputText);

    // 5. Inject Smart Schedule Events into Calendar
    const calendarKey = 'learny-calendar-custom-events';
    const existingEventsRaw = localStorage.getItem(calendarKey);
    const existingEvents = existingEventsRaw ? JSON.parse(existingEventsRaw) : [];

    const dueDate = smartSchedule?.dueDate || new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
    const dueTime = smartSchedule?.dueTime || '11:59 PM';
    const dueReason = smartSchedule?.dueReason || 'Assignment Submission';

    // 5a. Deadline Event
    const deadlineEvent = {
      id: `hw-${classItem.id}-${Date.now()}`,
      title: `${classItem.courseCode}: ${summary}`,
      courseName: classItem.courseName,
      date: dueDate,
      time: dueTime,
      type: 'homework',
      category: 'submission',
      description: `Target: ${dueReason} • Assigned: ${inputText}`,
    };

    const updatedEvents = existingEvents.filter((e: any) => e.id !== deadlineEvent.id);
    updatedEvents.push(deadlineEvent);

    // 5b. Prep Session Event (if generated by LLM)
    if (smartSchedule?.prepBlock) {
      const prepEvent = {
        id: `prep-${classItem.id}-${Date.now()}`,
        title: `🧠 ${smartSchedule.prepBlock.title || `${classItem.courseCode} Prep`}`,
        courseName: classItem.courseName,
        date: smartSchedule.prepBlock.date || dueDate,
        time: smartSchedule.prepBlock.time || '07:00 PM',
        type: 'study',
        category: 'prep',
        description: smartSchedule.prepBlock.description || `Study block for ${classItem.courseName}`,
      };
      updatedEvents.push(prepEvent);
    }

    localStorage.setItem(calendarKey, JSON.stringify(updatedEvents));

    // 6. Push to Cloud Firestore & Server Ledger
    pushToFirestore({
      problemsMap: { [classItem.courseId]: problems, mth203: problems },
      backlogHomeworkMap: {
        [classItem.id]: {
          rawInput: inputText,
          summary,
          problems,
          dueDate,
          courseCode: classItem.courseCode,
          courseName: classItem.courseName,
        },
      },
    });

    try {
      fetch('/api/homework/sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          lectureId: classItem.id,
          courseCode: classItem.courseCode,
          courseName: classItem.courseName,
          rawInput: inputText,
          summary,
          problems,
          dueDate,
          dueTime,
          smartSchedule,
        }),
      }).catch((e) => console.warn('Server sync error', e));
    } catch {}

    setSavedSuccess(true);
    setTimeout(() => {
      onSaved(summary);
      onClose();
    }, 1000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm">
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 8 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.96, y: 8 }}
        transition={{ duration: 0.15 }}
        className="w-full max-w-lg rounded-2xl bg-zinc-950 border border-zinc-800 p-5 space-y-4 shadow-2xl overflow-hidden"
      >
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
          <div className="space-y-0.5">
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-mono text-zinc-400">
                {classItem.courseCode} • {classItem.room}
              </span>
            </div>
            <h3 className="text-sm font-semibold text-white">
              Log Homework: {classItem.courseName}
            </h3>
          </div>

          <button
            onClick={onClose}
            className="rounded-lg p-1 text-zinc-400 hover:text-white transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {savedSuccess ? (
          <div className="py-8 text-center space-y-2">
            <CheckCircle2 className="h-10 w-10 text-emerald-400 mx-auto animate-bounce" />
            <h4 className="text-sm font-semibold text-white">
              Homework Formatted &amp; Scheduled on Calendar!
            </h4>
            <p className="text-xs text-zinc-400">
              Intelligence layer mapped deadline &amp; focus sessions into your timetable.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Input Form */}
            <form onSubmit={handleFormatWithAI} className="space-y-3">
              <div className="space-y-1">
                <label className="text-xs font-medium text-zinc-300">
                  Assigned Homework (Type notes or shorthand):
                </label>
                <div className="flex gap-2">
                  <Input
                    value={inputText}
                    onChange={(e) => setInputText(e.target.value)}
                    placeholder={
                      classItem.courseCode.includes('MTH')
                        ? 'e.g. 14.2 3 5, 14.3 2 (Thomas Calculus)'
                        : classItem.courseCode.includes('CSE231')
                        ? 'e.g. CPU Scheduling sheet Q1-4, Lab 1'
                        : classItem.courseCode.includes('CSE201')
                        ? 'e.g. Lab 1 Polymorphic hierarchy, Design Patterns'
                        : 'e.g. Reading summary 1, Activity 1'
                    }
                    className="bg-zinc-900 border-zinc-800 text-xs font-mono flex-1 h-9"
                    required
                  />

                  <Button
                    type="submit"
                    disabled={loading || !inputText.trim()}
                    className="h-9 bg-white text-zinc-950 hover:bg-zinc-200 text-xs font-semibold px-3.5 gap-1.5 shrink-0"
                  >
                    {loading ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    ) : (
                      <Sparkles className="h-3.5 w-3.5" />
                    )}
                    <span>Format with AI</span>
                  </Button>
                </div>
                <div className="text-[11px] text-zinc-500">
                  Type what was assigned in {classItem.courseCode} ({classItem.courseName})
                </div>
              </div>
            </form>

            {/* Live KaTeX & Smart Schedule Preview Block */}
            {previewData && (
              <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-3.5 space-y-3 max-h-64 overflow-y-auto scrollbar-thin">
                <div className="flex items-center justify-between text-xs border-b border-zinc-800 pb-2">
                  <span className="font-semibold text-white flex items-center gap-1.5">
                    <Sparkles className="h-3.5 w-3.5 text-zinc-300" />
                    <span>Formatted Homework ({previewData.problems?.length || 0})</span>
                  </span>
                  <span className="text-[10px] text-zinc-400 font-mono">Gemini AI</span>
                </div>

                {/* Smart Timetable Schedule Breakdown */}
                {previewData.smartSchedule && (
                  <div className="p-2.5 rounded-lg bg-zinc-950 border border-zinc-800/80 space-y-1.5 text-xs">
                    <div className="flex items-center justify-between text-[11px]">
                      <span className="font-semibold text-emerald-400 flex items-center gap-1">
                        <CalendarPlus className="h-3.5 w-3.5" />
                        <span>Scheduled Deadline</span>
                      </span>
                      <span className="font-mono text-zinc-300 text-[10px]">
                        {previewData.smartSchedule.dueDate} @ {previewData.smartSchedule.dueTime}
                      </span>
                    </div>
                    <p className="text-[11px] text-zinc-400">
                      <strong>Target: </strong>
                      {previewData.smartSchedule.dueReason}
                    </p>
                    {previewData.smartSchedule.prepBlock && (
                      <div className="pt-1 border-t border-zinc-900 flex items-center justify-between text-[10px] text-zinc-400">
                        <span>🧠 Prep: {previewData.smartSchedule.prepBlock.title}</span>
                        <span className="text-zinc-300 font-mono">{previewData.smartSchedule.prepBlock.time}</span>
                      </div>
                    )}
                  </div>
                )}

                {/* Problem Items */}
                <div className="space-y-2">
                  {previewData.problems?.map((p: any, idx: number) => (
                    <div
                      key={idx}
                      className="p-2.5 rounded-lg bg-zinc-950 border border-zinc-800/80 space-y-1.5"
                    >
                      <div className="flex items-center justify-between text-[11px]">
                        <span className="font-semibold text-zinc-200">
                          {p.exercise} — Q{p.qNum}: {p.title}
                        </span>
                        <span className="text-zinc-500 font-mono text-[10px]">{p.difficulty}</span>
                      </div>

                      {p.latex && (
                        <div className="py-1 px-2 rounded bg-zinc-900 text-center text-xs overflow-x-auto">
                          <MathView math={p.latex} displayMode={true} />
                        </div>
                      )}

                      {p.methodOfWork && (
                        <p className="text-[11px] text-zinc-400 leading-relaxed">
                          <strong className="text-zinc-300">Method: </strong>
                          {p.methodOfWork}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Modal Actions */}
            <div className="flex items-center justify-between pt-2 border-t border-zinc-800">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={onClose}
                className="text-xs text-zinc-400 hover:text-white"
              >
                Cancel
              </Button>

              <div className="flex gap-2">
                {previewData && (
                  <Button
                    type="button"
                    size="sm"
                    onClick={handleConfirmSave}
                    className="bg-white text-zinc-950 hover:bg-zinc-200 text-xs font-semibold px-4 gap-1.5"
                  >
                    <CheckCircle2 className="h-3.5 w-3.5" />
                    <span>Save &amp; Schedule on Calendar</span>
                  </Button>
                )}
              </div>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
}
